apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: guqing-higan
  annotations:
    store.halo.run/app-id: app-eiTyL
spec:
  displayName: 彼岸
  author:
    name: guqing
    website: https://guqing.io
  description: 生死为此岸，涅槃为彼岸；有苦无乐为此岸，无苦无乐为彼岸...它代表着对一切美好的精神追求，也代表着生生不息的轮回亦如本主题分黑白两色，阴极阳至，向死而生。
  logo: /themes/guqing-higan/assets/images/logo.png
  website: https://guqing.io
  repo: https://github.com/guqing/halo-theme-higan
  settingName: guqing-higan-setting
  configMapName: guqing-higan-configmap
  version: 2.10.0
  requires: ">=2.19.0"
  license:
    - name: "MIT"
      url: "https://github.com/guqing/halo-theme-higan/blob/main/LICENSE"
